### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Matthysse** [EndlesNights/TorchSlab#12]
Hello !
I have an error from Forge on game startup :
[https://pastebin.com/wt6gUPLU](url)

**Comment by EndlesNights** [comment]
The error is saying that that "YELLOW_HIBISCUS_SCENTED_CANDLE" does not exist, which is a reference call to the BuzzierBees mod. Have you downloaded a newer version of that mod? I don't see any updates on there CurseForged page, but if  you have a version other than BuzzierBees  1.4 that could be causing the the issues. since if they removed or changed the name of that blocks registry it would cause an error.

As a stop gap I'll put up some proper error catching to just skip over blocks that don't exist instead of crashing on start up.

**Comment by Matthysse** [comment]
Oh yes, it must be that, I didn't thought of it. And yes it would be nice !

**Comment by EndlesNights** [comment]
Alright here is a kick dirty early version you can try out that just skips the parts with error. I still would like to change a few other things for a full release that will give me informative debugging message in the future.

[torchslabmod-1.15.2_v1.6.9 PRE.zip](https://github.com/EndlesNights/TorchSlab/files/4555514/torchslabmod-1.15.2_v1.6.9.PRE.zip)
