### ISSUE TITLE
Torches can be placed partially inside other blocks

### ISSUE THREAD

**Issue by WenXin20** [EndlesNights/TorchSlab#4]
`Minecraft v1.14.4`
`Torch Slab v1.4`

If there is a block above it, the torch can still be placed. A check probably needs to be added to make sure the block is air above it.
![2020-02-08_21 56 52](https://user-images.githubusercontent.com/12000593/74122510-2b7a5500-4b91-11ea-8b21-41bd17facec5.png)

**Comment by EndlesNights** [comment]
So I wasn't using a check for air because I thought there were a a number of instances were there could be none air blocks above the top torch such as:
![2020-02-11_14 44 36](https://user-images.githubusercontent.com/58280840/74272750-2cb89880-4cdd-11ea-8b8b-b53310c64c6d.png)
Anyway I ended up using a short hand by checking if the blocks bottom face was a none solid face, which created a number of inconsistency such as the one you pointed out. Current version has been updated to do a more robust check.
